### ISSUE TITLE
Get error trying to delete post

### ISSUE THREAD

**Issue by test0n3** [rahmanfadhil/flask-rest-api#1]
Greetings, I was following your article and got an error
```
AttributeError: 'Post' object has no attribute 'delete'
```
It indicated the following line:
https://github.com/rahmanfadhil/flask-rest-api/blob/1f83783a21e0906e765e3704462936da6e4be00b/main.py#L64

Got some advice from this article: 
https://stackoverflow.com/questions/4921038/deleting-row-with-flask-sqlalchemy

Thanks for the article.

**Comment by rahmanfadhil** [comment]
Wow, thanks to spot an error!

It should be:
```python
db.session.delete(post)
```
