### ISSUE TITLE
Error on delete

### ISSUE THREAD

**Issue by ccxx72** [rahmanfadhil/flask-rest-api#3]
def delete(self, post_id):
        post = Post.query.get_or_404(post_id)
        post.delete()
        db.session.commit()
        return '', 204

It should be:
def delete(self, post_id):
        post = Post.query.get_or_404(post_id)
        db.session.delete(post_id)
        db.session.commit()
        return '', 204

**Comment by rahmanfadhil** [comment]
Oops, I forgot to update the repo when I update the article, thanks! 😃
